---
title: "Briefing Note: New statistical evidence that early help and family support spending reduces intervention rates and two illustrative case studies of investment"
description: |
  New research under review in the Journal of Social Policy suggests that higher spending on early help and family support was associated with fewer Children in Need in local authorities, and that this finding was statistically significant. On average, each £20 spent per child over the year was associated with a 1 per 10,000 fall in Children in Need rates the following year. Using publicly released data, two case studies of councils that have made a commitment to either re-invest in, or protect their early intervention funding, have been presented to illustrate possible effects of early help and family support funding. These councils have seen dramatic reductions in children looked-after rates, which may have saved tens of millions of pounds.
author:
  - name: Calum Webb
    url: www.calumwebb.uk
    affiliation: The University of Sheffield
    affiliation_url: https://www.sheffield.ac.uk/socstudies/people/academic-staff/calum-webb
    orcid_id: 0000-0001-7521-2110
citation_url: https://www.calumwebb.uk/ehfs_briefing_note.html
bibliography: "../data_resources/biblio.bib"
csl: "../data_resources/the-open-university-numeric-superscript.csl"
date: 10-21-2020
output: distill::distill_article

---

**Disclaimer**: This research is currently under peer review. Please email c.j.webb@sheffield.ac.uk for a pre-review version of the research paper.

## What does existing research about the effects of investing in early help and family support show?
Existing research about early help and family support such as meta-analyses of Randomised Controlled Trials and observational studies by the National Audit Office and Ofsted tend to show that early help and family support programmes improve many aspects of health and wellbeing for parents and children,[@layzer2001national; @dagenais2004impact] but that there is no larger correlation between investment in these services and rates of intervention (Children in Need, Child Protection Plans, Children Looked After, etc.)[@nao2016children; @nao2019pressures; @ofsted2017annual] This means there is usually a poor financial case for investing in early help and family support services, even though there is a lot of qualitative evidence about how they are valued by social workers and families.[@mason2012social] These services have been cut by more than 50% per child on average over the last ten years.[@webb2018austerity; @webb2020app]

## What does this new research suggest?
This new research suggests that there is a causal 'lagged effect' of investment in non-safeguarding, non-children looked-after services, on Children in Need rates. This means that when spending on early help and family support services increases in one year, there is a significant decrease in Children in Need (Section 17) rates the following year. For every £20 spent per child on these services there was an average 1 per 10,000 reduction in Children in Need rates the following year. To put this in perspective, this suggests that if spending on these services had stayed at 2010/2011 levels throughout the decade and thresholds remained the same, we would have expected to see around 21% fewer Children in Need in 2018/2019 than there currently are. This would have meant fewer knock-on child protection plans and child removals, because in most routine circumstances children must be found to be 'in Need' before they can be placed on a protection plan. 

## Why is this finding so different to the NAO and Ofsted's findings?
This finding is more accurate than previous analyses because it fixes a methodological problem with the kinds of analysis that are usual done on children's services data. Normally, analyses rely on looking at patterns between local authorities that share similar characteristics. For example, do local authorities with higher spending per child also have lower Children in Need rates. This is problematic even when other factors are controlled for because local authorities will often use different thresholds for Section 17 and these thresholds will be systematically linked to how much funding they have available. Lower available funding tends to lead to higher thresholds and more rationing. There will also usually be general national patterns, such as consistent reductions in spending over time everywhere, that can bias the estimates in statistical models for detecting lagged effects. This breaks the common interpretations we rely on for making sense of trends from traditional statistical analyses, like cross-lagged panel models, linear regression models or correlations. This new research adjusts for these problems while retaining sample size and generalisability by focusing on within-local authority patterns using a complex model developed in clinical statistics called an 'ALT-SR' model.[@curran2014separation; @mund2019beyond]


## Case Study Local Authorities

**Disclaimer:** These case studies have been written based on publicly available data about the local authority/health and social care board. They are not necessarily reflective of the local government organisations' own interpretation of the data and have not been endorsed by them or developed with them formally. They should not be taken as precise estimates, especially when this relates to cost savings from children looked-after reductions. Averages are used where possible but the profile of the reduction in children in care and the kinds of support they need is not known, and therefore more precise costs cannot be calculated. Many children looked-after in Scotland also remain with their birth family, which may mean that estimates of effects are inflated when comparisons are made with English local authorities. While the causal effect has been identified in the new research, there are also likely other factors unrelated to early help and family support spending that can explain councils' reductions in intervention, including express commitments from leaders to pursue this. These case studies are intended to be illustrative only and aim to demonstrate why greater investment in early help and family support should be seriously considered as a mechanism to reduce child protection and child removal interventions.

### Camden [@webb2020app; @camdenNDearly]

The London Borough of Camden has been a significant outlier in terms of its spending on Early Help and Family Support and in its trajectory in children looked-after rates. Its total spending on non-safeguarding, non-looked-after services has fluctuated between around £30million and £36million between 2010 and 2019, adjusting for inflation. This is particularly unusual for a mid-to-high deprivation local authority, nearly all of which have cut their early help and family support services.[@webb2018austerity] 

Since 2016, Camden has had the highest spending per child on family support and early help of any local authority in England. At the same time, Camden have reduced their rates of children in care every single year since 2011: from 73 per 10,000 in 2010-11 to 37.5 per 10,000 in 2018/19, a reduction of almost half. They were one of only 48 local authorities to see decreases on average each year rather than increases. More than this, Camden has actually seen the second highest average yearly reduction in children looked-after rates in the entire country (-4.66 per 10,000 per year), and Camden's yearly reductions have been far more consistent than the local authority with the highest yearly reductions, Haringey (-4.86 per 10,000 per year). Camden's per year reduction was more than 3 times greater than the average for the 48 (-1.49 per 10,000 per year). One of the consequences of this is that Camden has been able to keep its total spending on children looked-after very stable. The average local authority in England saw their total spending on children looked-after increase from around £23million in 2010-11 to £32.5million in 2018-19. By contrast, Camden's spending has fluctuated between £19.2million and £30.7million over the decade, rather than increasing in one direction, with the last 5 years of the decade being between £23million and £25million. Overall, Camden's total children looked-after spending is about £2million higher in 2018-19 than it was in 2010-11, compared to the average £9.5million higher in all local authorities on average.

In 2018-19, Camden's child population was estimated to be around 51,000 and their average spend per child looked-after was £124,000 per year, 175 times higher than the cost per child on early help and family support. Based on this, we might estimate that Camden had 175[^The fact these are both 175 is coincidence.] fewer children looked-after in 2018-19 than it otherwise would have had if rates of children in care had stayed at their 2010-11 levels. This would have carried an additional associated cost of £21.7million per year, almost doubling what Camden's looked-after children spending currently is and being about ten times more than the actual increase they in children looked-after costs that they experienced.

This has been possible in part due to Camden Council's commitment to early help and family support services. Stemming from Camden Resilient Families, the Camden Social Work Model saw the council provide a well-resourced (relative to the rest of the country) early help service that includes a range of support, designed to reimagine family support as a way to actively promote the welfare of children, not just protect them from harm. This includes dedicated early help coordinators and longer term (6 months plus) support, enabling family workers to develop relationships with families and identify effective solutions to their problems in partnership with them, through practices like family group conferencing. Crucially, this includes being meaningfully connected with wider forms of community support and community organisations in a way that is only possible with long-term investments and commitments. These organisations and collective groups often respond to families' practical needs, many of which are associated with poverty: food, clothing, laundry, fuel, loneliness, and participation in cultural events.[@townsend1979poverty; @dove2020someone] 

Camden's approach reflects an implementation of social work theory that enables families and children to flourish, on their own terms with respect to their feelings and desires.[@white2014re; @featherstone2018protecting] It often targets the social determinants of family conflict before problems develop but, importantly, the service does not appear to be *prescriptive* about this remit - the resources and support offered are largely family-centred and family-led. The focus is on the relationship between the family, the worker, and the problem, not on the specific therapy on offer or its effectiveness. The service has increased social services contact with families but this increased contact has not translated into greater statutory intervention into family life, as is often the case, with referral rates, children in need rates, and children looked-after rates all falling by at least 40% since 2010-11. Although there has been an increase of around 25% in Child Protection Plan rates since 2014, rates are still below what they were in 2010-11.

You can find out more about the Camden model of social work [here](https://www.camdenchildrenssocialwork.info/pages/camden-model-of-social-work).

### Glasgow[@cpcgNDimprovement; @glasgowNDintegrated; @burnsNDtackling; @mckennaNDfamily; @scotgovNDchildrens]

Glasgow City Health and Social Care Partnership implemented a strategic plan to improve children's services, reduce the numbers of children in care, especially those placed outside of the city, and to address the role that poverty was having on entry into the child protection system in 2017. Key to this was identifying 'failure demand' in their service ecosystem, and the fact that families were becoming increasingly unable to secure the early help and support they needed and being pulled into the child protection system as a final resort, either after problems had escalated or because they had nowhere else to turn. Before implementing the plan, Glasgow had the highest rate of children looked after in Scotland, even after controlling for child deprivation, at around 327 children per 10,000. The city's Children and Young People’s Integrated Service Plan 2017-2020 saw a renewed commitment to providing early help and family support, especially to address the root causes of child neglect associated with poverty, referencing the Child Welfare Inequalities Project.

Glasgow committed to redirecting funding to early intervention and family support programmes in the plan, as part of this investing an additional £1.98million into early intervention, prevention, and family support into the city (around £7 extra per child in Glasgow per year of the three year plan). This was a significant increase in spending on these kinds of services, with the explicit aim of a whole-city approach to tackling neglect and its association with poverty (1 in 3 children are living in deprivation in Glasgow).

By 2018-19 the rate of children looked after in Glasgow had reduced to around 250 per 10,000, an enormous reduction of just over 23% in three years. This would have translated to around 770 fewer children in care, based on the Glasgow child population. While there are few good estimates of the costs associated with care, the CWIP App estimates for England that the average cost in a local authority is around £65,000 per child per year. At this approximation, we could then estimate that Glasgow's integrated plan and £1.98million of additional funding to early intervention and family support saved around £50million per year in children looked-after costs - not to mention the non-financial benefits of keeping families together and providing them adequate support. Even if the costs associated with care were as low as the lowest costs in a local authority England in 2018-19 (North East Lincolnshire at £36,252 per child per year), the savings would still have been around £27.9million per year, 14 times greater than the largest 3-year additional contribution of spending in the plan.





